# Generated by Django 4.2.6 on 2024-05-21 11:53

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', User.models.CustomUserManager()),
            ],
        ),
    ]
